### ISSUE TITLE
Tutorial for marker gene identification

### ISSUE THREAD

**Issue by liuchunlei0430** [SindiLab/N-ACT#5]
Dear authors, thank you for making the code resource available to the public!

I am interested in exploring the identification of marker genes from this paper, but I didn’t find the tutorial corresponding to that part. 
 
I would be very much appreciate it if you could help.
 
Many thanks.

**Comment by dr-aheydari** [comment]
Hi @liuchunlei0430,

Thank you very much for your interest in NACT! You can definitely choose the top `n` features (marker genes) using NACT. The idea would be to use the top `n` *attentive genes* that the model identifies as the most important global features. 

Apologies for the late response; we were cleaning up the code a bit and changing the docstrings. We just released a new version of NACT, and we will soon add a tutorial on how to pick the top global features. 

I will send another reply here with the link to the tutorial in the coming days!

**Comment by dr-aheydari** [comment]
Hi @liuchunlei0430,

I just added two tutorial notebooks on using NACT to [select global markers](https://github.com/SindiLab/Tutorials/tree/main/N-ACT/Global%20Feature%20Selection) and [perform broad annotations (in a sense local marker gene selection)](https://github.com/SindiLab/Tutorials/tree/main/N-ACT/Annotation%20and%20Enrichment%20Tests). I will be adding additional tutorials for NACT's other capabilities as week in the coming days.

I hope these tutorials help. Please let me know if you have any questions : )

(I'm closing this issue for now, but please feel free to reopen it if you have any other questions)

**Comment by liuchunlei0430** [comment]
Thanks for your sharing!!! Could I ask where the training code is? I didn't find the files about training the models.

**Comment by dr-aheydari** [comment]
Of course! The training scripts are located at https://github.com/SindiLab/N-ACT-TrainingScripts <https://github.com/SindiLab/N-ACT-TrainingScripts> 

Thanks again for being patient and apologies for the package and the code being a little out of place! We are getting ready for a preprint so we have been redoing a major portion of N-ACT!

---
Ali Heydari (he/him)
NIH NRSA Fellow
Applied Mathematics Ph.D. Candidate

***@***.***
www.ali-heydari.com
